### ISSUE TITLE
[Question] admin API and maintenance

### ISSUE THREAD

**Issue by haoyuhu** [aasailan/egg-nideshop#1]
It's a nice project for me! :smile: But I have several questions below:
* I can't find admin API which is implemented by [tumobi/nideshop](https://github.com/tumobi/nideshop/tree/master/src/admin) in your project.
* Some important logic parts are not implemented.

Will you continue to maintain and improve this project?
If not, can you hand over the project to me or set me as a collaborator. I will keep on maintaining this project.
Thank you for your wonderful project!

**Comment by aasailan** [comment]
hello，i am sorry that i am too busy to maintain this project. and i will set you a collaborator later. good luck
签名由网易邮箱大师定制
On 6/14/2019 12:49，hahahu<notifications@github.com> wrote：

It's a nice project for me! 😄 But I have several questions below:

I can't find admin API which is implemented by tumobi/nideshop in your project.
Some important logic parts are not implemented.

Will you continue to maintain and improve this project?
If not, can you hand over the project to me or set me as a collaborator. I will keep on maintaining this project.
Thank you for your wonderful project!

**Comment by haoyuhu** [comment]
Thank you for fast reply. 😆
